apply plugin: 'com.github.ben-manes.versions'

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
        def ghUser = System.getenv("GITHUB_USERNAME")
        def ghToken = System.getenv("GITHUB_TOKEN")
        if (ghUser && ghToken) {
            maven {
                url = uri("https://maven.pkg.github.com/twofortyfouram/android-monorepo")
                credentials {
                    username = ghUser
                    password = ghToken
                }
            }
        }
    }
    dependencies {
        classpath group:'com.android.tools.build', name:'gradle', version: '8.3.2'
        classpath group:'com.github.ben-manes', name:'gradle-versions-plugin', version:'0.46.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        def ghUser = System.getenv("GITHUB_USERNAME")
        def ghToken = System.getenv("GITHUB_TOKEN")
        if (ghUser && ghToken) {
            maven {
                url = uri("https://maven.pkg.github.com/twofortyfouram/android-monorepo")
                credentials {
                    username = ghUser
                    password = ghToken
                }
            }
        }
    }

    // Forces all dependencies to be resolved.  Useful in continuous integration
    // to populate the dependency cache.
    // https://discuss.gradle.org/t/download-all-dependencies/6294
    task resolveAllDependencies {
        doLast {
            configurations.all { it.resolve() }
        }
    }

    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << '-Xlint:all'
        }
    }
}
